# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: true
sudo: false
pandoc: false
cache: packages
os:
  - linux
  - osx
osx_image: xcode12.5
env:
  global:
    - _R_CHECK_DONTTEST_EXAMPLES_=FALSE